{
 "title": "Libvirt - VMs",
 "tags": [ "os" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Region", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Caution / Hints",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "content": "\nMake sure not to select a huge time range with all VMs and all graphs open -> that might kill your browser. \n\n\nSelect VMs / Disks / Network Interfaces by opening the corresponding row and clicking in the table.\n"
  },
  {
   "title": "libvirt Collector Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(libvirt_up == 0)", "legendFormat": "broken" },
    { "expr": "count(libvirt_up == 1)", "legendFormat": "ok" }
   ]
  },
  {
   "title": "VM State",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(libvirt_domain_info_vstate == 1)",
     "legendFormat": "running"
    },
    {
     "expr": "count(libvirt_domain_info_vstate == 2)",
     "legendFormat": "blocked on resource"
    },
    {
     "expr": "count(libvirt_domain_info_vstate == 3)",
     "legendFormat": "paused"
    },
    {
     "expr": "count(libvirt_domain_info_vstate == 4)",
     "legendFormat": "shutting down"
    },
    {
     "expr": "count(libvirt_domain_info_vstate == 5)",
     "legendFormat": "shutoff"
    }
   ]
  },
  {
   "title": "Disk Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (disk_type)(libvirt_domain_block_meta)",
     "legendFormat": "{{ disk_type }}"
    }
   ]
  },
  {
   "title": "Disk Bus",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (bus)(libvirt_domain_block_meta)",
     "legendFormat": "{{ bus }}"
    }
   ]
  },
  {
   "title": "Disk Cache",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (cache)(libvirt_domain_block_meta)",
     "legendFormat": "{{ cache }}"
    }
   ]
  },
  {
   "title": "VM Selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select VM",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      { "expr": "libvirt_domain_info_meta" }
     ]
    }
   ]
  },
  {
   "title": "Disk Selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select Disk",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      { "expr": "libvirt_domain_block_meta" }
     ]
    }
   ]
  },
  {
   "title": "Network Interface Selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select Network Interface",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "libvirt_domain_interface_meta" }
     ]
    }
   ]
  },
  {
   "title": "CPU & RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_info_cpu_time_seconds_total[$interval])) * 100 / sum(libvirt_domain_info_virtual_cpus) ",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(libvirt_domain_info_maximum_memory_bytes)",
       "legendFormat": "RAM Limit"
      },
      {
       "expr": "sum(libvirt_domain_info_memory_usage_bytes)",
       "legendFormat": "RAM Usage"
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_memory_stats_major_fault_total[$interval]))",
       "legendFormat": "major_fault"
      },
      {
       "expr": "sum(rate(libvirt_domain_memory_stats_minor_fault_total[$interval]))",
       "legendFormat": "minor_fault"
      }
     ]
    },
    {
     "title": "RAM Sizes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(libvirt_domain_memory_stats_rss_bytes)",
       "legendFormat": "Qemu Process Size"
      },
      {
       "expr": "sum(libvirt_domain_memory_stats_available_bytes)",
       "legendFormat": "Available to VM"
      },
      {
       "expr": "sum(libvirt_domain_memory_stats_unused_bytes)",
       "legendFormat": "Unused"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & RAM Top",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_info_cpu_time_seconds_total[$interval]) * 100 / libvirt_domain_info_virtual_cpus",
       "legendFormat": "{{ project_name }} - {{ instance_name }} - {{ uuid }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_virtual_cpus",
       "legendFormat": "{{ project_name }} - {{ instance_name }} - {{ uuid }}"
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_memory_stats_major_fault_total[$interval])",
       "legendFormat": "major_fault {{ project_name }} - {{ instance_name }} - {{ uuid }}"
      },
      {
       "expr": "rate(libvirt_domain_memory_stats_minor_fault_total[$interval])",
       "legendFormat": "minor_fault {{ project_name }} - {{ instance_name }} - {{ uuid }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total[$interval])) ",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total[$interval])) ",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk I/O Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(libvirt_domain_block_stats_read_requests_total[$interval])) ",
       "legendFormat": "read"
      },
      {
       "expr": "sum (rate(libvirt_domain_block_stats_write_requests_total[$interval])) ",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_time_seconds_total[$interval])) * 100 / count(libvirt_domain_block_stats_read_time_seconds_total)",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_time_seconds_total[$interval])) * 100 / count(libvirt_domain_block_stats_write_time_seconds_total)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(libvirt_domain_block_stats_capacity_bytes)",
       "legendFormat": "Size"
      },
      {
       "expr": "sum(libvirt_domain_block_stats_allocation)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Flush Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_flush_time_seconds_total[$interval])) * 100 / count(libvirt_domain_block_stats_read_time_seconds_total)",
       "legendFormat": "flush"
      }
     ]
    },
    {
     "title": "Flush Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(libvirt_domain_block_stats_flush_requests_total[$interval])) ",
       "legendFormat": "flush"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Top",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_block_stats_read_bytes_total[$interval])",
       "legendFormat": "read  {{ project_name }} - {{ instance_name }} - {{ uuid }} - {{ target_device }}"
      },
      {
       "expr": "rate(libvirt_domain_block_stats_write_bytes_total[$interval])",
       "legendFormat": "write {{ project_name }} - {{ instance_name }} - {{ uuid }} - {{ target_device }}"
      }
     ]
    },
    {
     "title": "Disk I/O Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_block_stats_read_requests_total[$interval])",
       "legendFormat": "read  {{ project_name }} - {{ instance_name }} - {{ uuid }} - {{ target_device }}"
      },
      {
       "expr": "rate(libvirt_domain_block_stats_write_requests_total[$interval])",
       "legendFormat": "write  {{ project_name }} - {{ instance_name }} - {{ uuid }} - {{ target_device }}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_block_stats_read_time_seconds_total[$interval]) * 100 ",
       "legendFormat": "read  {{ project_name }} - {{ instance_name }} - {{ uuid }} - {{ target_device }}"
      },
      {
       "expr": "rate(libvirt_domain_block_stats_write_time_seconds_total[$interval]) * 100",
       "legendFormat": "write {{ project_name }} - {{ instance_name }} - {{ uuid }} - {{ target_device }}"
      }
     ]
    },
    {
     "title": "Flush Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_block_stats_flush_requests_total[$interval])",
       "legendFormat": "{{ project_name }} - {{ instance_name }} - {{ target_device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total[$interval])) ",
       "legendFormat": "receive"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total[$interval])) ",
       "legendFormat": "transmit"
      }
     ]
    },
    {
     "title": "Network I/O Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total[$interval])) ",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total[$interval])) ",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Network I/O Drops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total[$interval])) ",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total[$interval])) ",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Network I/O Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_errors_total[$interval])) ",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_errors_total[$interval])) ",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Top",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(rate(libvirt_domain_interface_stats_receive_bytes_total[$interval])) ",
       "legendFormat": "receive  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      },
      {
       "expr": "(rate(libvirt_domain_interface_stats_transmit_bytes_total[$interval])) ",
       "legendFormat": "transmit  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      }
     ]
    },
    {
     "title": "Network I/O Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "(rate(libvirt_domain_interface_stats_receive_packets_total[$interval])) ",
       "legendFormat": "read  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      },
      {
       "expr": "(rate(libvirt_domain_interface_stats_transmit_packets_total[$interval])) ",
       "legendFormat": "write  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      }
     ]
    },
    {
     "title": "Network I/O Drops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "(rate(libvirt_domain_interface_stats_receive_drops_total[$interval])) ",
       "legendFormat": "read  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      },
      {
       "expr": "(rate(libvirt_domain_interface_stats_transmit_drops_total[$interval])) ",
       "legendFormat": "write  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      }
     ]
    },
    {
     "title": "Network I/O Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "(rate(libvirt_domain_interface_stats_receive_errors_total[$interval])) ",
       "legendFormat": "read  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      },
      {
       "expr": "(rate(libvirt_domain_interface_stats_transmit_errors_total[$interval])) ",
       "legendFormat": "write  {{ project_name }} - {{ instance_name }} - {{ uuid }} -  {{ target_device }}"
      }
     ]
    }
   ]
  }
 ]
}